routes:
  - path: /users
    service: users

  - path: /products
    service: products

  - path: /orders
    service: orders

services:
  users:
    strategy: roundRobin

    instances:
      - host: localhost
        port: 8001

      - host: localhost
        port: 8002

  products:
    strategy: random

    instances:
      - host: localhost
        port: 8003
      - host: localhost
        port: 8004

  orders:
    strategy: leastConnections

    instances:
      - host: localhost
        port: 8005
      - host: localhost
        port: 8006