routes:
  - path: /users
    service: users

  - path: /products
    service: products

  - path: /payments
    service: payments

services:
  users:
    strategy: leastConnections

    cache:
      enabled: false
      ttl: 10

    instances:
      - host: users1
        port: 8001

      - host: users2
        port: 8001

  products:
    strategy: random

    cache:
      enabled: false
      ttl: 10

    instances:
      - host: products1
        port: 8001
      - host: products2
        port: 8001

  payments:
    strategy: leastConnections

    cache:
      enabled: true
      ttl: 60

    instances:
      - host: payments1
        port: 8001
      - host: payments2
        port: 8001
      